### ISSUE TITLE
[Question] How to install Zorin DE in Debian?

### ISSUE THREAD

**Issue by asddsaz** [ZorinOS/zorin-desktop-themes#1]
So, my understand is that Zorin DE is just some themes on GNOME3.
Therefore you can install it on any OS where GNOME3 is supported without the use of any extra proprietary software.

What are the installation steps for installing Zorin DE on Debian?

**Comment by ArtyomZorin** [comment]
The Zorin OS desktop themes can be installed by either copying the theme folders into your system's `/usr/share/themes` directory, or installing the latest Zorin OS desktop themes debian package (https://launchpad.net/~zorinos/+archive/ubuntu/stable/+files/zorin-desktop-themes_2.0.8_all.deb) from the Zorin OS repositories.

Please note that the Zorin desktop environment actually comprises of a large number of packages, apps and Gnome Shell extensions in addition to the themes. In order to get the full Zorin desktop experience, we would recommend you to install Zorin OS, which is based indirectly on Debian (as it's based directly on Ubuntu).
