### ISSUE TITLE
Gnome shell extension not getting themed

### ISSUE THREAD

**Issue by 0mega28** [ZorinOS/zorin-desktop-themes#12]
Applied ZorinGrey-Dark theme
Using it on Manjaro 21.1.0 Gnome
![image](https://user-images.githubusercontent.com/43883288/130440992-577fba94-e87c-472e-a9e9-9ffe05a5d8c8.png)

**Comment by DeeBeeDouble** [comment]
Yeah that's because it doesn't support GTK4 yet and this is using GTK4. If you want to use it with GTK4 theming, just download a theme with GTK4 support and take the folder "gtk-4.0" from the theme you just downloaded and put in in the Zorin theme folder. Then re-enable the theme. I did it and it isn't perfect but it is better than the standard GTK4 theme. I hope it helps ;)

**Comment by hmlendea** [comment]
Another workaround is to create/edit the `~/.config/gtk-4.0/settings.ini` and set `gtk-application-prefer-dark-theme=1` which will at least make the application Dark. It will still use the Adwaita theme instead of the Zorin theme though. But at least you won't have to download additional themes and maintain them each update.
