### ISSUE TITLE
Title bar radius on full screen.

### ISSUE THREAD

**Issue by roxshivamsingh** [ZorinOS/zorin-desktop-themes#26]
I am a Zorin Pro user.

Apps like Chrome, VSCode, Postman contain radius on full screen it is weird to see gaps between them on full screen.

In Zorin Pro, nothing is seems like pro or premium. It inherit all ubuntu bugs and UI glitches.

![2022-07-22_13-08](https://user-images.githubusercontent.com/56290347/180388970-85d5e372-5fd1-43cc-93ab-85eb7c3d9ecf.png)

**Comment by ArtyomZorin** [comment]
As Chrome is a third-party app which doesn't use the standard GTK toolkit, this is an issue that will need to be resolved by the Chrome developers. It happens with other GTK desktop themes as well.

In my testing, Electron apps like VSCode and Postman don't show curved corners when snapped to the left or right of the screen (see screenshot below), so they behave correctly.
![Screenshot from 2022-07-22 22-23-42](https://user-images.githubusercontent.com/3945334/180570757-2f2098ed-0985-4309-ae26-3a975ae7fb3f.png)

Please make sure to move the window to the very left or right of the screen so that it snaps to take up that half of the screen in order to remove the rounded corners. If doing so still shows curved corners for you, we would recommend you to install the latest updates from the Software Updater app and Software store.

**Comment by roxshivamsingh** [comment]
[window-change.webm](https://user-images.githubusercontent.com/56290347/180593936-1c1cc02c-0b9f-42dc-a7e3-827e8830e75e.webm)
