### ISSUE TITLE
Support fro Libadwaita

### ISSUE THREAD

**Issue by dawgsome** [ZorinOS/zorin-desktop-themes#27]
So, while non-Libadwaita GTK 4.0 apps are themed correctly using this workaround: https://github.com/ZorinOS/zorin-desktop-themes/issues/10#issuecomment-1007138782 , if I then paste the files in the gtk-4.0 / 3.0 folder into .config/gtk-4.0/, apps look like this: 
![Screenshot from 2022-07-26 15-34-53](https://user-images.githubusercontent.com/91278118/181039629-601862a3-f383-4a93-b16a-bd23608294ee.png)
![image](https://user-images.githubusercontent.com/91278118/181039727-3378bc06-d920-4ae0-8bed-a5610c8ec4f2.png)

**Comment by ArtyomZorin** [comment]
We are planning to add support for GTK 4 and libadwaita to the Zorin desktop themes in time for the release of Zorin OS 17 in 2023.

**Comment by dawgsome** [comment]
Oh OK, thank you

2 Aug 2022 19:45:21 Artyom Zorin ***@***.***>:

**Comment by DartDeaDia** [comment]
> We are planning to add support for GTK 4 and libadwaita to the Zorin desktop themes in time for the release of Zorin OS 17 in 2023.

I think a better solution would be to provide a default Adwaita theme from the GNOME platform by default.
Perhaps you've heard about https://stopthemingmy.app

I think you would agree that default Adwaita style provides the best user experience.
Using a custom font and system icons can ruin the appearance of applications, because GTK/Libadwaita apps are designed by following the GNOME HIG.


Of course, you will probably be against it, because it would reduce the recognizability of Zorin.
But, you can continue to use own App icons (that out-the-box) and Folders/Files icons, to remain Zorin recognizability and provide the best experience of using apps.

**Comment by ArtyomZorin** [comment]
Support for libadwaita theming is now added in the new 4.0 release of this theme, alongside a patch to the libadwaita package in the upcoming Zorin OS 17.

Only first-party and system-installed libadwaita apps are styled with the Zorin theme (and compatible third-party themes) as part of this patch. All Flatpak apps that are built with libadwaita will continue to use the standard theme, without Zorin theme styling.
